#将Disqus注释的“注释”更改为true
迪斯克斯:
评论: 错误的
disqus_shortname: 'detem'

#如果您没有使用Google Analytics，请将“google-ID”更改为空字符串
谷歌标识: UA-112060364-2 '

菜单:

- {名字: '学习资源',全球资源定位器(Uniform Resource Locator): '资源'}
- {名字: '示例帖子',全球资源定位器(Uniform Resource Locator): '示例-帖子'}
- {名字: '文档',全球资源定位器(Uniform Resource Locator): '文档'}
- {名字: 关于,全球资源定位器(Uniform Resource Locator): 关于}
- {名字: '联系人',全球资源定位器(Uniform Resource Locator): '联系人'}

#可用的社交图标由字体Awesome支持，因此您可以使用他们提供的任何图标
社会的:
- {图标: “zhihu”,环:    ' https://www.zhihu.com/people/li-qi-ming-39-49 '}
- {图标: “douyin”,环:   ' https://www.douyin.com/user/self?from_tab_name=main%29 '}
- {图标: ' instagram ',环:  ' https://insta gram . com/paululele '}
- {图标: '信封',环:   mailto:hello@paulle.ca '}
- {图标: ' rss-square ',环: feed.xml '}
# - {icon: 'rss-square '，link: 'rss-feed.xml'}

#自定义网站文本
页码:
下一页: '更新'
上一页_页面: “更老”

分享_按钮_提示: 请随意分享！

相关_帖子: 你也可以享受...

邮政日期前缀: 写于'
